version: "3.8"

services: # OpenWebUI
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      # - /Users/ai/openwebui-dify/openwebui:/app/backend/data
      - volume_openwebui:/app/backend/data
    restart: always
    networks:
      - shared_bridge_network

  # pipelines
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    ports:
      - "9099:9099"
    volumes:
      # - /Users/ai/openwebui-dify/pipelines:/app/pipelines
      - volume_pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - shared_bridge_network

volumes:
  volume_openwebui:
  volume_pipelines:
  
networks:
  shared_bridge_network:
    driver: bridge